# Generated by Django 5.2.7 on 2025-12-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('cta', models.CharField(blank=True, max_length=80)),
                ('image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_profile', to='tenants.tenantprofile')),
            ],
            options={
                'verbose_name': 'Perfil do catálogo',
                'verbose_name_plural': 'Perfis do catálogo',
            },
        ),
    ]
