# Generated by Django 5.2.7 on 2026-01-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogprofile",
            name="desktop_image",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="catalogprofile",
            name="mobile_image",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
