# Generated by Django 5.2.7 on 2025-12-10 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_negocio', models.CharField(blank=True, max_length=120, verbose_name='Nome do negócio')),
                ('slug', models.SlugField(blank=True, help_text='Usado na URL pública da papelaria.', max_length=80, null=True, unique=True, verbose_name='Slug público')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('access_end_date', models.DateField(blank=True, null=True, verbose_name='Expiração da assinatura')),
                ('is_active', models.BooleanField(default=True, verbose_name='Conta ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de papelaria',
                'verbose_name_plural': 'Perfis de papelaria',
                'ordering': ['-created_at'],
            },
        ),
    ]
