# Generated by Django 5.2.7 on 2025-12-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0003_subcategoria_produto_subcategoria_variacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
