# Generated by Django 6.0 on 2025-12-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_perf_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='categoria',
            name='categoria_tenant',
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='prod_tenant_ativo',
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='prod_categoria',
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='prod_subcategoria',
        ),
        migrations.RemoveIndex(
            model_name='subcategoria',
            name='subcat_tenant',
        ),
        migrations.RemoveIndex(
            model_name='variacao',
            name='var_produto',
        ),
    ]
